name: sonido
description: "A multiplatform music player app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  go_router: ^17.3.0
  just_audio: ^0.10.5
  on_audio_query:
    git:
      url: https://github.com/rozpo/on_audio_query
      ref: 0d78299
      path: packages/on_audio_query
  path_provider: ^2.1.0
  audio_service: ^0.18.0
  rxdart: ^0.27.0
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.2
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
